version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/tools"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
